services:
  heroku-cli:
    build: ./heroku
    env_file: ./heroku/.env

  db:
    build: ./resources/database
    env_file: .env
    volumes:
      - projectwebsite-db:/var/lib/postgresql/data
      - ./resources/database:/docker-entrypoint-initdb.d
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: devapp
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

    command: "npm start"

volumes:
  projectwebsite-db: {}